/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NewDOF (https://sketchfab.com/dof_new)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imitation-classroom-stage-b2a393020cee4f54b61cca70ea95ac35
Title: Imitation classroom stage
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Classroom(props) {
  const { nodes, materials } = useGLTF("/imitation_classroom_stage.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["02___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["07___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["03___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["05___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["06___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["08___Default"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/imitation_classroom_stage.glb");

