/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aashutosh Dabhade (https://sketchfab.com/adabhade17)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-lady-character-3500e52341194c94b51b73edd260c662
Title: Office lady Character
*/

import React, {useEffect, useRef} from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";

export function Lady(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/office_lady_character.glb");

  const {animations : talkingAnimation} = useFBX('animations/Talking.fbx')
  console.log(talkingAnimation)
  talkingAnimation[0].name = "Talking"
  

  const {actions} = useAnimations(talkingAnimation, group)

  console.log(talkingAnimation[0].tracks);

  useEffect(()=>{
    actions["Talking"].reset().play()
  },[])

  

  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.Object_7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_9.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.Object_9.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_11.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Object_11.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_13.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Object_13.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_15.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Object_15.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_17.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Object_17.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_19.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Object_19.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_21.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Object_21.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_23.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Object_23.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/office_lady_character.glb");
